sudo: required
services:
  - docker

before_install:
  - docker build -t enok/docker-react -f Dockerfile.dev .

script:
  - docker run enok/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-sa-east-1-466610009895"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"